{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ff3cb0b4-3d19-4347-b309-b20a109fa026",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import messagebox\n",
    "import random\n",
    "\n",
    "# --------------------------\n",
    "# Global Variables\n",
    "# --------------------------\n",
    "words = []               \n",
    "word = \"\"              \n",
    "guessed_letters = []    \n",
    "attempts = 6             \n",
    "hint_limit = 0          \n",
    "hints_used = 0         \n",
    "\n",
    "# GUI elements\n",
    "root = None\n",
    "word_label = None\n",
    "letter_entry = None\n",
    "attempts_label = None\n",
    "hints_label = None\n",
    "canvas = None\n",
    "\n",
    "# --------------------------\n",
    "# Start Window\n",
    "# --------------------------\n",
    "def start_window(): \n",
    "    global root\n",
    "    root = tk.Tk()\n",
    "    root.title(\"Hangman Game\")\n",
    "    root.geometry(\"400x500\")\n",
    "    root.configure(bg=\"orange\")\n",
    "\n",
    "    tk.Label(root, text=\"HANGMAN\", font=(\"Chiller\", 35, \"bold\"), bg=\"orange\", fg=\"blue\").pack(pady=50)\n",
    "    tk.Button(root, text=\"Start Game\", font=(\"Jokerman\", 18), command=start_difficulty,\n",
    "              bg=\"green\", fg=\"white\", bd=8, relief=\"ridge\", width=10).pack(pady=10)\n",
    "    tk.Button(root, text=\"Exit\", font=(\"Jokerman\", 16, \"bold\"), command=root.destroy,\n",
    "              bg=\"red\", fg=\"white\", bd=8, relief=\"ridge\", width=8).pack(pady=10)\n",
    "\n",
    "    root.mainloop()\n",
    "\n",
    "# --------------------------\n",
    "# Difficulty Selection Window\n",
    "# --------------------------\n",
    "def start_difficulty():\n",
    "    root.destroy() \n",
    "    diff_window = tk.Tk()\n",
    "    diff_window.title(\"Choose Difficulty\")\n",
    "    diff_window.geometry(\"400x500\")\n",
    "    diff_window.configure(bg=\"peach puff\")\n",
    "\n",
    "    tk.Label(diff_window, text=\"Select Difficulty Level\", font=(\"Jokerman\", 18), bg=\"peach puff\").pack(pady=25)\n",
    "\n",
    "    # Load words based on difficulty\n",
    "    def set_difficulty(level):\n",
    "        global words\n",
    "        filename = f\"{level}.txt\"\n",
    "        try:\n",
    "            with open(filename, \"r\") as file:\n",
    "                words.clear()\n",
    "                words.extend([line.strip().lower() for line in file.readlines()])\n",
    "        except FileNotFoundError:\n",
    "            messagebox.showerror(\"Error\", f\"{filename} not found!\")\n",
    "            diff_window.destroy()\n",
    "            return\n",
    "\n",
    "        if not words:\n",
    "            messagebox.showerror(\"Error\", f\"{filename} is empty!\")\n",
    "            return\n",
    "\n",
    "        diff_window.destroy()\n",
    "        start_game()\n",
    "\n",
    "    tk.Button(diff_window, text=\"Easy\", width=20, font=(\"Jokerman\", 14),\n",
    "              bg=\"gold\", command=lambda: set_difficulty(\"easy\")).pack(pady=8)\n",
    "    tk.Button(diff_window, text=\"Medium\", width=20, font=(\"Jokerman\", 14),\n",
    "              bg=\"orange\", command=lambda: set_difficulty(\"medium\")).pack(pady=8)\n",
    "    tk.Button(diff_window, text=\"Hard\", width=20, font=(\"Jokerman\", 14),\n",
    "              bg=\"coral\", command=lambda: set_difficulty(\"hard\")).pack(pady=8)\n",
    "\n",
    "    tk.Button(diff_window, text=\"Main Menu\", font=(\"Jokerman\", 14),\n",
    "              bg=\"sky blue\", command=lambda: [diff_window.destroy(), start_window()]).pack(pady=12)\n",
    "\n",
    "    diff_window.mainloop()\n",
    "\n",
    "# --------------------------\n",
    "# Game Window\n",
    "# --------------------------\n",
    "def start_game():\n",
    "    global word, guessed_letters, attempts, hint_limit, hints_used\n",
    "    global root, word_label, letter_entry, attempts_label, hints_label, canvas\n",
    "\n",
    "    word = random.choice(words)  # Pick a word\n",
    "    guessed_letters = []\n",
    "    attempts = 6\n",
    "    hints_used = 0\n",
    "\n",
    "    # Determine hint limit based on word length\n",
    "    length = len(word)\n",
    "    if 3 <= length <= 5:\n",
    "        hint_limit = 1\n",
    "    elif 6 <= length <= 9:\n",
    "        hint_limit = 2\n",
    "    else:\n",
    "        hint_limit = 3\n",
    "\n",
    "    # Create game window\n",
    "    root = tk.Tk()\n",
    "    root.title(\"Hangman Game\")\n",
    "    root.geometry(\"400x650\")\n",
    "    root.configure(bg=\"peach puff\")\n",
    "\n",
    "    canvas = tk.Canvas(root, width=200, height=250, bg=\"white\")\n",
    "    canvas.pack(pady=20)\n",
    "    draw_base()\n",
    "\n",
    "    # Word display\n",
    "    word_label = tk.Label(root, text=\"_ \" * len(word), font=(\"Papyrus\", 20), bg=\"peach puff\")\n",
    "    word_label.pack(pady=20)\n",
    "    update_word_display()\n",
    "\n",
    "    # Letter input\n",
    "    letter_entry = tk.Entry(root, bg=\"peach puff\", font=(\"Papyrus\", 14), bd=4, relief=\"ridge\")\n",
    "    letter_entry.pack(pady=12)\n",
    "    letter_entry.focus()\n",
    "\n",
    "    # Buttons for Guess and Hint\n",
    "    btn_frame = tk.Frame(root, bg=\"peach puff\")\n",
    "    btn_frame.pack(pady=15)\n",
    "    tk.Button(btn_frame, text=\"Guess\", font=(\"Jokerman\", 12), command=guess_letter, bg=\"light blue\").pack(side=\"left\", padx=8)\n",
    "    tk.Button(btn_frame, text=\"Hint\", font=(\"Jokerman\", 12), command=use_hint, bg=\"orange\").pack(side=\"left\", padx=8)\n",
    "\n",
    "    # Attempts and hints display\n",
    "    attempts_label = tk.Label(root, text=f\"Attempts left: {attempts}\", font=(\"Papyrus\", 13,\"bold\"), bg=\"peach puff\")\n",
    "    attempts_label.pack(pady=6)\n",
    "    hints_label = tk.Label(root, text=f\"Total Hints: {hint_limit}\", font=(\"Papyrus\", 13,\"bold\"), bg=\"peach puff\")\n",
    "    hints_label.pack(pady=6)\n",
    "\n",
    "    # Menu buttons\n",
    "    menu_frame = tk.Frame(root, bg=\"peach puff\")\n",
    "    menu_frame.pack(pady=15)\n",
    "    tk.Button(menu_frame, text=\"Main Menu\", font=(\"Jokerman\", 12),\n",
    "              bg=\"sky blue\", command=lambda: [root.destroy(), start_window()]).pack(side=\"left\", padx=12)\n",
    "    tk.Button(menu_frame, text=\"Exit\", font=(\"Jokerman\", 12),\n",
    "              bg=\"red\", fg=\"white\", command=root.destroy).pack(side=\"left\", padx=12)\n",
    "\n",
    "    root.mainloop()\n",
    "\n",
    "# --------------------------\n",
    "# Draw Hangman Base\n",
    "# --------------------------\n",
    "def draw_base():\n",
    "    canvas.delete(\"all\")\n",
    "    canvas.create_line(20, 230, 180, 230, width=2)\n",
    "    canvas.create_line(50, 230, 50, 20, width=2)\n",
    "    canvas.create_line(50, 20, 150, 20, width=2)\n",
    "    canvas.create_line(150, 20, 150, 40, width=2)\n",
    "\n",
    "def draw_hangman(wrong):\n",
    "    # Draw hangman parts based on number of wrong guesses\n",
    "    if wrong >= 1: canvas.create_oval(135, 40, 165, 70, width=2)  # head\n",
    "    if wrong >= 2: canvas.create_line(150, 70, 150, 130, width=2) # body\n",
    "    if wrong >= 3: canvas.create_line(150, 80, 120, 100, width=2) # left arm\n",
    "    if wrong >= 4: canvas.create_line(150, 80, 180, 100, width=2) # right arm\n",
    "    if wrong >= 5: canvas.create_line(150, 130, 120, 170, width=2) # left leg\n",
    "    if wrong >= 6: canvas.create_line(150, 130, 180, 170, width=2) # right leg\n",
    "    \n",
    "# --------------------------\n",
    "# Game Logic\n",
    "# --------------------------\n",
    "def update_word_display():\n",
    "    # Show guessed letters and underscores\n",
    "    display_word = \"\"\n",
    "    for letter in word:\n",
    "        display_word += letter + \" \" if letter in guessed_letters else \"_ \"\n",
    "    word_label.config(text=\"enter a letter\\n\" + display_word)\n",
    "\n",
    "def guess_letter():\n",
    "    global attempts\n",
    "    letter = letter_entry.get().lower().strip()\n",
    "    letter_entry.delete(0, tk.END)\n",
    "\n",
    "    # Validate input\n",
    "    if len(letter) != 1 or not letter.isalpha():\n",
    "        messagebox.showwarning(\"Invalid Input\", \"Please enter ONE alphabet letter.\")\n",
    "        return\n",
    "    if letter in guessed_letters:\n",
    "        messagebox.showinfo(\"Hangman\", \"You already guessed that letter!\")\n",
    "        return\n",
    "\n",
    "    guessed_letters.append(letter)\n",
    "\n",
    "    # Wrong guess\n",
    "    if letter not in word:\n",
    "        attempts -= 1\n",
    "        attempts_label.config(text=f\"Attempts left: {attempts}\")\n",
    "        draw_hangman(6 - attempts)\n",
    "\n",
    "    update_word_display()\n",
    "    check_game_over()\n",
    "\n",
    "def use_hint():\n",
    "    global hints_used\n",
    "    if hints_used >= hint_limit:\n",
    "        messagebox.showinfo(\"Hint\", \"No hints remaining!\")\n",
    "        return\n",
    "    remaining = [l for l in word if l not in guessed_letters]\n",
    "    if not remaining:\n",
    "        messagebox.showinfo(\"Hint\", \"No letters left to reveal!\")\n",
    "        return\n",
    "    guessed_letters.append(random.choice(remaining))\n",
    "    hints_used += 1\n",
    "    hints_label.config(text=f\"Total Hints : {hint_limit - hints_used}\")\n",
    "    update_word_display()\n",
    "    check_game_over()\n",
    "\n",
    "def check_game_over():\n",
    "    # Check win\n",
    "    if all(l in guessed_letters for l in word):\n",
    "        messagebox.showinfo(\"Hangman\", \"Congratulations! You won!\")\n",
    "        root.destroy()\n",
    "    # Check lose\n",
    "    elif attempts <= 0:\n",
    "        draw_hangman(6)\n",
    "        messagebox.showinfo(\"Hangman\", f\"You lost! The word was '{word}'\")\n",
    "        root.destroy()\n",
    "\n",
    "# --------------------------\n",
    "# Start Program\n",
    "# --------------------------\n",
    "start_window()\n"
   ]
  },
  {
   "cell_type": "raw",
   "id": "f88f03ae-eca3-40c8-9702-b9dc338c8012",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "04666807-49e2-49e7-98ba-d1f10cda73d8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "798d526a-7dd1-4360-8a69-e9ada65a1982",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ce934492-73a3-4c1a-9179-f0b249e53cb0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4f8ef844-e93e-4562-9954-729424991f56",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
